name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Checar o código
      - name: Check out the code
        uses: actions/checkout@v2

      # Passo 2: Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, zip, pdo, pdo_sqlite
          coverage: xdebug

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          
      # Passo 3.1: Setar o arquivo de ambiente para testing
      - name: Set environment file to testing
        run: |
          cp .env.testing .env      

      # Passo 4: Garantir que o banco de dados SQLite exista
      - name: Create SQLite database if not exists
        run: |
          touch database/database.sqlite

      # Passo 5: Rodar as migrações e os testes
      - name: Run migrations and tests
        run: |
          php artisan key:generate --env=testing
          php update-jwt-secret.php
          php artisan migrate
          php artisan test
