name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: LaravelPipe
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 020385
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Passo 1: Checar o código
      - name: Check out the code
        uses: actions/checkout@v2

      # Passo 2: Configurar PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, zip, pdo, pdo_pgsql
          coverage: xdebug

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          
     # Passo 3.1: Enveriment test
      - name: Set environment file to testing
        run: |
          cp .env.testing .env      

      # Passo 4: Configurar o banco de dados (caso esteja usando PostgreSQL no CI)
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for database..."
            sleep 2
          done

      # Passo 5: Rodar as migrações e os testes
      - name: Run migrations and tests
        run: |
          php artisan migrate
          php artisan test 

     # Passo 7: Deploy (opcional)
      # - name: Deploy to production server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" | ssh-add -
      #     ssh user@your-server 'cd /caminho/do/projeto && git pull && composer install && php artisan migrate'
